#!/usr/bin/env python3
r"""Run the full optimiser/RL comparison on one city/bbox → §10 table.

Implements OPTIMIZER_SPEC §11 item 6 / §12 DoD ("the §10 reporting table can
be generated by a single CLI command"). Loads a small city's bike + walk
graphs, extracts candidates once (shared by all solvers and the RL env —
§8 fairness), runs greedy / greedy+local-search / ILP, optionally trains a
small MaskablePPO and scores it with the shared ``objective``, then prints
and writes the §10 reporting table.

By default the comparison uses a **monotone coverage-only objective** so
that the ILP ceiling is valid and greedy's submodular guarantee holds.
Use ``--weighted-objective`` to reproduce prior objective-sensitivity
findings with the legacy weighted objective
(``0.4·conn + 0.4·cov − 0.2·frag``); on that non-monotone objective greedy
can stall mid-construction and RL may appear to beat it — see
``FINDINGS.md`` for the full diagnosis. ``--coverage-only`` is accepted as
a backward-compatible no-op (it is now the default).

Examples:
    # Optimisers only (no RL training); fast. Coverage-only default.
    python scripts/run_comparison.py --city "Otley, UK" --budget 200000

    # Include a small RL row (trains ~4096 timesteps first).
    python scripts/run_comparison.py --city "Otley, UK" --budget 200000 \\
        --with-rl --timesteps 4096 --n-envs 2

    # Reproduce the legacy weighted-objective diagnostic.
    python scripts/run_comparison.py --city "Otley, UK" --budget 200000 \\
        --weighted-objective

    # Tiny bbox for a quick sanity check.
    python scripts/run_comparison.py --bbox 53.9065 53.9045 -1.6929 -1.6949 \\
        --budget 100000 --with-rl --timesteps 2048
"""

from __future__ import annotations

import argparse
import logging
import sys
import time
from pathlib import Path

# Ensure the repo root is importable when run as `python scripts/...`.
_REPO_ROOT = Path(__file__).resolve().parents[1]
if str(_REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(_REPO_ROOT))

from bike_rl.config import Config  # noqa: E402
from bike_rl.graph_utils import configure_osm_cache, load_bbox_graph, load_city_graph  # noqa: E402
from bike_rl.objective import ObjectiveWeights  # noqa: E402
from bike_rl.optim.evaluate import (  # noqa: E402
    build_instance_from_graphs,
    format_comparison_table,
    run_comparison,
)
from bike_rl.run_context import RunContext  # noqa: E402

logger = logging.getLogger("run_comparison")


def _build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(
        description="Run optimiser/RL comparison and emit the §10 table.",
    )
    g = p.add_mutually_exclusive_group(required=True)
    g.add_argument("--city", type=str, help="City name for OSMnx download")
    g.add_argument(
        "--bbox",
        type=float,
        nargs=4,
        metavar=("N", "S", "E", "W"),
        help="Bounding box (N S E W)",
    )
    p.add_argument("--budget", type=float, default=200_000.0)
    p.add_argument("--seed", type=int, default=0)
    p.add_argument("--out-dir", type=str, default="bike_path_figures")
    p.add_argument(
        "--with-rl",
        action="store_true",
        help="Train a small MaskablePPO and add an 'rl' row to the table.",
    )
    p.add_argument("--timesteps", type=int, default=4096, help="RL training timesteps")
    p.add_argument("--n-envs", type=int, default=2, help="RL training envs")
    obj_grp = p.add_mutually_exclusive_group()
    obj_grp.add_argument(
        "--coverage-only",
        action="store_true",
        help=(
            "Use coverage-only weights (now the default; accepted for "
            "backward compatibility)."
        ),
    )
    obj_grp.add_argument(
        "--weighted-objective",
        action="store_true",
        help=(
            "Use the legacy weighted objective (0.4·conn + 0.4·cov − 0.2·frag) "
            "instead of the default coverage-only metric. Use this to reproduce "
            "prior objective-sensitivity findings; on that non-monotone objective "
            "greedy can stall mid-construction."
        ),
    )
    p.add_argument("--ilp-time-limit", type=float, default=60.0)
    p.add_argument(
        "--max-candidates",
        type=int,
        default=None,
        help="Cap candidates to the top-N by road priority (keeps LS/ILP tractable).",
    )
    p.add_argument(
        "--ls-time-limit",
        type=float,
        default=60.0,
        help="Local-search wall-time limit in seconds.",
    )
    p.add_argument("--verbose", action="store_true")
    return p


def _objective_weights(args: argparse.Namespace) -> ObjectiveWeights:
    """Select objective weights based on CLI flags.

    Coverage-only is the default (monotone submodular — matches the ILP
    ceiling and greedy's guarantee). ``--weighted-objective`` opts into the
    legacy weighted objective for objective-sensitivity / reproducibility
    runs. ``--coverage-only`` is a backward-compatible no-op (it is now the
    default).
    """
    if args.weighted_objective:
        return ObjectiveWeights()
    return ObjectiveWeights(connectivity=0.0, coverage=1.0, fragmentation=0.0)


def _label(args: argparse.Namespace) -> str:
    if args.city:
        base = args.city
    else:
        n, s, e, w = args.bbox
        base = f"bbox_{n}_{s}_{e}_{w}"
    out = "".join(ch if ch.isalnum() else "_" for ch in base.lower())
    while "__" in out:
        out = out.replace("__", "_")
    return out.strip("_")


def _load_graphs(args: argparse.Namespace, cfg: Config):
    configure_osm_cache(cfg)
    if args.city:
        bike = load_city_graph(args.city, cfg, network_type="bike")
        walk = load_city_graph(args.city, cfg, network_type="walk")
    else:
        n, s, e, w = args.bbox
        bike = load_bbox_graph(n, s, e, w, cfg, network_type="bike")
        walk = load_bbox_graph(n, s, e, w, cfg, network_type="walk")
    return bike, walk


def _maybe_train_rl(args: argparse.Namespace, bike, walk, cfg: Config, run_context: RunContext):
    """Train a small MaskablePPO and return the model (or None)."""
    if not args.with_rl:
        return None
    from stable_baselines3.common.vec_env import SubprocVecEnv

    from bike_rl.training import make_vec_env, train_model

    envs = make_vec_env(
        bike,
        walk,
        cfg,
        run_context,
        n_envs=args.n_envs,
        seed=cfg.seed,
        budget=args.budget,
        vec_env_cls=SubprocVecEnv,
    )
    try:
        model = train_model(envs, cfg, run_context, args.timesteps)
    finally:
        envs.close()
    return model


def main(argv: list[str] | None = None) -> int:
    """Run the comparison and emit the §10 table (entry point).

    Args:
        argv: Optional CLI args (defaults to ``sys.argv[1:]``).

    Returns:
        0 on success, 1 if no candidates are extracted.
    """
    args = _build_parser().parse_args(argv)
    logging.basicConfig(
        level=logging.INFO if args.verbose else logging.WARNING,
        format="%(levelname)s:%(name)s:%(message)s",
        stream=sys.stdout,
    )

    cfg = Config(
        seed=args.seed,
        ilp_time_limit_s=args.ilp_time_limit,
        local_search_time_limit_s=args.ls_time_limit,
    )
    weights = _objective_weights(args)

    run_context = RunContext.create(Path(args.out_dir), f"compare_{_label(args)}")
    run_context.ensure_output_dir()

    t0 = time.perf_counter()
    bike, walk = _load_graphs(args, cfg)
    logger.info(
        "loaded graphs: bike |V|=%d |E|=%d  walk |V|=%d |E|=%d",
        bike.number_of_nodes(),
        bike.number_of_edges(),
        walk.number_of_nodes(),
        walk.number_of_edges(),
    )

    instance = build_instance_from_graphs(bike, walk, cfg, weights, args.budget, label=_label(args))
    if args.max_candidates is not None and len(instance.candidates) > args.max_candidates:
        instance.candidates = instance.candidates[: args.max_candidates]
        logger.info("capped candidates to top-%d by road priority", args.max_candidates)
    logger.info(
        "instance %s: %d candidates, budget=%.0f, weights=%s",
        instance.label,
        len(instance.candidates),
        instance.budget,
        weights,
    )

    if not instance.candidates:
        print(f"[run_comparison] no candidates extracted for {instance.label}; aborting.")
        return 1

    rl_model = _maybe_train_rl(args, bike, walk, cfg, run_context)

    sols = run_comparison(instance, rl_policy=rl_model)
    table = format_comparison_table(sols, instance)
    load_s = time.perf_counter() - t0

    # ── Sanity check (OPTIMIZER_SPEC §1 / §11 item 6) ──
    by = {s.solver: s for s in sols}
    obj_mode = "weighted (legacy)" if args.weighted_objective else "coverage-only (default)"
    diagnosis = ""
    if "rl" in by and "greedy" in by:
        g_obj = by["greedy"].objective
        r_obj = by["rl"].objective
        if r_obj > g_obj + 1e-9:
            diagnosis = (
                f"\n\n**Sanity check ({obj_mode}):** RL ({r_obj:.4f}) > greedy "
                f"({g_obj:.4f}). On the coverage-only objective greedy has a "
                "submodular guarantee (≥63%), so this is unexpected — investigate "
                "RL reward shaping or candidate-set fairness. On the weighted "
                "objective the non-monotone fragmentation penalty can make greedy "
                "stall; use `--weighted-objective` to reproduce that diagnostic."
            )
        else:
            gap = (g_obj - r_obj) / g_obj if g_obj > 0 else 0.0
            diagnosis = (
                f"\n\n**Sanity check ({obj_mode}):** greedy ({g_obj:.4f}) ≥ RL "
                f"({r_obj:.4f}) — RL is {gap * 100:.1f}% behind greedy. This is the "
                "expected result on the coverage-only objective (greedy's "
                "submodular guarantee vs a lightly-trained PPO with "
                f"{args.timesteps} timesteps). Increase --timesteps or tune PPO "
                "hyperparameters for a closer race. ⚠️"
            )
    elif "rl" not in by:
        diagnosis = "\n\n**Sanity check:** no RL row (--with-rl not set); greedy/LS/ILP only."

    report = table + diagnosis + f"\n\n*Total wall time: {load_s:.1f}s.*"
    print("\n" + report + "\n")

    out_file = run_context.output_dir / "comparison_table.md"
    out_file.write_text(report + "\n")
    print(f"[run_comparison] table written to {out_file}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
